import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar
          links={[
            { text: "Home", href: "#" },
            { text: "About us", href: "#about" },
            { text: "Pricing", href: "#pricing" },
            { text: "Features", href: "#features" },
          ]}
          logoUri="/images/logo.svg"
          button={{
            link: "https://youtube.com",
            text: "Download Now",
          }}
        />
        {children}
      </body>
    </html>
  );
}
